/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import CapaPresentacion.FrmConcultas;
import CapaPresentacion.jDialogCliente;

import CapaPresentacion.jdiCategoria;
import CapaPresentacion.jdiLogin;
import CapaPresentacion.jdiProducto;
import CapaPresentacion.jdiTrabajador;
import CapaPresentacion.jdiVistaProducto;
import CapaPresentacion.jdiaRegistrarReserva;
import CapaPresentacion.jdialogRegistroHabitaciones;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rojeru San
 */
public class PrincipalHotel extends javax.swing.JFrame {
    
    boolean b = true;
    private boolean minimiza = false;
    boolean verificarMenu = false;
    public static boolean cerra = false;
    int idTrabaj=12;
    String nombreTrab="juan ";

    /**
     * Creates new form Principal
     */
    public void palabrasClaves(int idTra, String nombreTra) {
        this.idTrabaj = idTra;
        this.nombreTrab = nombreTra;
    }
       private static PrincipalHotel instancia;

    public static PrincipalHotel getInstancia() {
        if(instancia==null){
            instancia = new PrincipalHotel();
        }
        return instancia;
    }
    
    
    
    public PrincipalHotel() {
               
        initComponents();
       
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo8.jpg")).getImage());
     
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        escritorioMenu.setBorder(new ImagenFondo());
        trans();
        visible();
    }
    
    public void cargarImagenesEnBotones() {
        boton1.setVisible(true);
        boton2.setVisible(true);
        boton3.setVisible(true);
        boton4.setVisible(true);
        cargado objeto;
        objeto = new cargado(boton1, boton2, boton3, boton4);
        objeto.start();
    }
    
    public void trans() {
        btnPrincipal.setOpaque(false);
        btnPrincipal.setBorderPainted(false);
        btnPrincipal.setContentAreaFilled(false);
    }
    
    void visible(){
        LblIdPrincipal.setVisible(false);
        lblAccesoUPrincipal.setVisible(false);
        lblMaternoUPrincipal.setVisible(false);
        lblNombreUPrincipal.setVisible(false);
        lblPaternoUPrincipal.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new principal.MaterialButton();
        minimizar = new principal.MaterialButton();
        jLabel1 = new javax.swing.JLabel();
        lblPaternoUPrincipal = new javax.swing.JLabel();
        lblNombreUPrincipal = new javax.swing.JLabel();
        lblAccesoUPrincipal = new javax.swing.JLabel();
        lblMaternoUPrincipal = new javax.swing.JLabel();
        LblIdPrincipal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cerrarSesion = new principal.MaterialButtomRectangle();
        btnPrincipal = new rojeru_san.RSButton();
        btnTrabajadores = new rojeru_san.RSButton();
        btnClientes = new rojeru_san.RSButton();
        btnHabitaciones = new rojeru_san.RSButton();
        btnCateogria = new rojeru_san.RSButton();
        btnProductos = new rojeru_san.RSButton();
        labelMetroICM1 = new com.icm.components.metro.LabelMetroICM();
        logoSexo = new javax.swing.JLabel();
        userConect1 = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        btnRserva = new rojeru_san.RSButton();
        Escritorio = new rojeru_san.RSPanelsSlider();
        escritorioMenu = new rojeru_san.RSPanelShadow();
        escritorioTodo = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        btnTrbajadoresTodo = new rojeru_san.RSButton();
        btnProductosTodo = new rojeru_san.RSButton();
        btnClientesTodo = new rojeru_san.RSButton();
        btnHabitacionesTodo = new rojeru_san.RSButton();
        btnCategoriaTodo = new rojeru_san.RSButton();
        jPanel5 = new javax.swing.JPanel();
        rSButton11 = new rojeru_san.RSButton();
        jPanel6 = new javax.swing.JPanel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 5));

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cerrar.setForeground(new java.awt.Color(255, 0, 0));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Cerrar</h4> </body> </html>");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        minimizar.setBackground(new java.awt.Color(255, 255, 255));
        minimizar.setForeground(new java.awt.Color(255, 0, 0));
        minimizar.setText("__");
        minimizar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Minimizar</h4> </body> </html>");
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        minimizar.setPreferredSize(new java.awt.Dimension(86, 77));
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema  De Control y Reserva  De Habitaciones Hotel- leaHotel");

        lblPaternoUPrincipal.setText("jLabel1");

        lblNombreUPrincipal.setText("jLabel1");

        lblAccesoUPrincipal.setText("jLabel1");

        lblMaternoUPrincipal.setText("jLabel1");

        LblIdPrincipal.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblIdPrincipal)
                .addGap(46, 46, 46)
                .addComponent(lblNombreUPrincipal)
                .addGap(18, 18, 18)
                .addComponent(lblPaternoUPrincipal)
                .addGap(18, 18, 18)
                .addComponent(lblMaternoUPrincipal)
                .addGap(18, 18, 18)
                .addComponent(lblAccesoUPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addComponent(minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblIdPrincipal)
                        .addComponent(lblNombreUPrincipal)
                        .addComponent(lblPaternoUPrincipal)
                        .addComponent(lblMaternoUPrincipal)
                        .addComponent(lblAccesoUPrincipal))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jPanel3.setBorder(dropShadowBorder1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VERSION 1.0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("© DERECHOS RESERVADOS 2017");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("leaHotel ");

        cerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesion.setText("CERRAR SESIÓN");
        cerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarSesion.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        btnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        btnPrincipal.setBorder(null);
        btnPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        btnPrincipal.setColorHover(new java.awt.Color(204, 204, 204));
        btnPrincipal.setColorText(new java.awt.Color(204, 204, 204));
        btnPrincipal.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        btnTrabajadores.setBackground(new java.awt.Color(102, 102, 102));
        btnTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal/icons8_Worker_45px_1.png"))); // NOI18N
        btnTrabajadores.setText("Trabajador");
        btnTrabajadores.setColorHover(new java.awt.Color(153, 153, 153));
        btnTrabajadores.setColorText(new java.awt.Color(204, 204, 204));
        btnTrabajadores.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnTrabajadores.setFont(new java.awt.Font("Roboto Bold", 1, 10)); // NOI18N
        btnTrabajadores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrabajadores.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajadoresActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(102, 102, 102));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal/17-48.png"))); // NOI18N
        btnClientes.setText("Cliente");
        btnClientes.setColorHover(new java.awt.Color(153, 153, 153));
        btnClientes.setColorText(new java.awt.Color(204, 204, 204));
        btnClientes.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnClientes.setFont(new java.awt.Font("Roboto Bold", 1, 10)); // NOI18N
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnHabitaciones.setBackground(new java.awt.Color(102, 102, 102));
        btnHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal/icons8_Bed_45px.png"))); // NOI18N
        btnHabitaciones.setText("Habitacion");
        btnHabitaciones.setColorHover(new java.awt.Color(153, 153, 153));
        btnHabitaciones.setColorText(new java.awt.Color(204, 204, 204));
        btnHabitaciones.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnHabitaciones.setFont(new java.awt.Font("Roboto Bold", 1, 10)); // NOI18N
        btnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionesActionPerformed(evt);
            }
        });

        btnCateogria.setBackground(new java.awt.Color(102, 102, 102));
        btnCateogria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal/icons8_Trolley_48px.png"))); // NOI18N
        btnCateogria.setText("Categoria");
        btnCateogria.setColorHover(new java.awt.Color(153, 153, 153));
        btnCateogria.setColorText(new java.awt.Color(204, 204, 204));
        btnCateogria.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnCateogria.setFont(new java.awt.Font("Roboto Bold", 1, 10)); // NOI18N
        btnCateogria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCateogriaActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(102, 102, 102));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal/icons8_Buying_45px.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setColorHover(new java.awt.Color(153, 153, 153));
        btnProductos.setColorText(new java.awt.Color(204, 204, 204));
        btnProductos.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnProductos.setFont(new java.awt.Font("Roboto Bold", 1, 10)); // NOI18N
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        labelMetroICM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conectado.png"))); // NOI18N

        logoSexo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descotectado1.png"))); // NOI18N

        userConect1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userConect1.setForeground(new java.awt.Color(255, 255, 255));
        userConect1.setText("USUARIO");

        desc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        desc.setForeground(new java.awt.Color(255, 255, 255));
        desc.setText("DESCONECTAR");
        desc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        desc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descMouseClicked(evt);
            }
        });

        btnRserva.setBackground(new java.awt.Color(102, 102, 102));
        btnRserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Hotel_18px.png"))); // NOI18N
        btnRserva.setText("Reserva");
        btnRserva.setColorHover(new java.awt.Color(153, 153, 153));
        btnRserva.setColorText(new java.awt.Color(204, 204, 204));
        btnRserva.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnRserva.setFont(new java.awt.Font("Roboto Bold", 1, 10)); // NOI18N
        btnRserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnCateogria, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMetroICM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userConect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(btnRserva, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMetroICM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userConect1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoSexo)
                    .addComponent(desc))
                .addGap(38, 38, 38)
                .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnCateogria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(633, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(34, 34, 34)))
        );

        Escritorio.setBackground(new java.awt.Color(240, 240, 240));
        Escritorio.setLayout(new javax.swing.BoxLayout(Escritorio, javax.swing.BoxLayout.LINE_AXIS));

        escritorioMenu.setBackground(new java.awt.Color(255, 255, 255));
        escritorioMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escritorioMenuMouseClicked(evt);
            }
        });

        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        btnTrbajadoresTodo.setBackground(new java.awt.Color(102, 102, 102));
        btnTrbajadoresTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal/icons8_Worker_45px_1.png"))); // NOI18N
        btnTrbajadoresTodo.setText("TRABAJADORES");
        btnTrbajadoresTodo.setColorHover(new java.awt.Color(153, 153, 153));
        btnTrbajadoresTodo.setColorText(new java.awt.Color(204, 204, 204));
        btnTrbajadoresTodo.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnTrbajadoresTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrbajadoresTodoActionPerformed(evt);
            }
        });

        btnProductosTodo.setBackground(new java.awt.Color(102, 102, 102));
        btnProductosTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal/icons8_Buying_45px.png"))); // NOI18N
        btnProductosTodo.setText("PRODUCTOS");
        btnProductosTodo.setColorHover(new java.awt.Color(153, 153, 153));
        btnProductosTodo.setColorText(new java.awt.Color(204, 204, 204));
        btnProductosTodo.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnProductosTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosTodoActionPerformed(evt);
            }
        });

        btnClientesTodo.setBackground(new java.awt.Color(102, 102, 102));
        btnClientesTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal/17-48.png"))); // NOI18N
        btnClientesTodo.setText("CLIENTES");
        btnClientesTodo.setColorHover(new java.awt.Color(153, 153, 153));
        btnClientesTodo.setColorText(new java.awt.Color(204, 204, 204));
        btnClientesTodo.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnClientesTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesTodoActionPerformed(evt);
            }
        });

        btnHabitacionesTodo.setBackground(new java.awt.Color(102, 102, 102));
        btnHabitacionesTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal/icons8_Bed_45px.png"))); // NOI18N
        btnHabitacionesTodo.setText("HABITACIONES");
        btnHabitacionesTodo.setColorHover(new java.awt.Color(153, 153, 153));
        btnHabitacionesTodo.setColorText(new java.awt.Color(204, 204, 204));
        btnHabitacionesTodo.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnHabitacionesTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionesTodoActionPerformed(evt);
            }
        });

        btnCategoriaTodo.setBackground(new java.awt.Color(102, 102, 102));
        btnCategoriaTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal/icons8_Trolley_48px.png"))); // NOI18N
        btnCategoriaTodo.setText("CATEGORIA");
        btnCategoriaTodo.setColorHover(new java.awt.Color(153, 153, 153));
        btnCategoriaTodo.setColorText(new java.awt.Color(204, 204, 204));
        btnCategoriaTodo.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnCategoriaTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTrbajadoresTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnProductosTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnClientesTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnHabitacionesTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnCategoriaTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHabitacionesTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientesTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductosTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrbajadoresTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoriaTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        escritorioTodo.addTab("MENU", jPanel4);

        rSButton11.setBackground(new java.awt.Color(102, 102, 102));
        rSButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal/Item_List-48.png"))); // NOI18N
        rSButton11.setText("REPORTES");
        rSButton11.setColorHover(new java.awt.Color(153, 153, 153));
        rSButton11.setColorText(new java.awt.Color(204, 204, 204));
        rSButton11.setColorTextHover(new java.awt.Color(204, 204, 204));
        rSButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(rSButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        escritorioTodo.addTab("REPORTES", jPanel5);

        javax.swing.GroupLayout escritorioMenuLayout = new javax.swing.GroupLayout(escritorioMenu);
        escritorioMenu.setLayout(escritorioMenuLayout);
        escritorioMenuLayout.setHorizontalGroup(
            escritorioMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioMenuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(escritorioTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        escritorioMenuLayout.setVerticalGroup(
            escritorioMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioMenuLayout.createSequentialGroup()
                .addContainerGap(377, Short.MAX_VALUE)
                .addComponent(escritorioTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        Escritorio.add(escritorioMenu);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        boton1.setBackground(new java.awt.Color(204, 204, 204));

        boton2.setBackground(new java.awt.Color(204, 204, 204));

        boton4.setBackground(new java.awt.Color(204, 204, 204));

        boton3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        this.setExtendedState(ICONIFIED);
        if (!minimiza) {
            minimiza = false;
            this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        } else {
            minimiza = true;
        }
    }//GEN-LAST:event_minimizarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Esta a punto de\ncerrar la sesión\n¿Desea continuar?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION, 0,
                new ImageIcon(getClass().getResource("/Imagenes/principal/preg2.png"))) == JOptionPane.YES_OPTION) {
            this.dispose();
            new jdiLogin().setVisible(true);
        }
    }//GEN-LAST:event_cerrarActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
        
        if (verificarMenu == false) {
            verificarMenu = true;
            escritorioTodo.setVisible(true);
        } else if (verificarMenu == true) {
            verificarMenu = false;
            escritorioTodo.setVisible(false);
        }

    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void btnTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajadoresActionPerformed
        try {
            jdiTrabajador d = new jdiTrabajador();
            d.toFront();
            d.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al acceder a la Aplicacion.", "Verifique el Error", 0);
            
        }

    }//GEN-LAST:event_btnTrabajadoresActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        try {
            jDialogCliente g = new jDialogCliente();
            g.toFront();
            g.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al acceder a la Aplicacion.", "Verifique el Error", 0);
        }
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionesActionPerformed
        try {
            jdialogRegistroHabitaciones f = new jdialogRegistroHabitaciones();
            f.toFront();
            f.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al acceder a la Aplicacion.", "Verifique el Error", 0);
        }

    }//GEN-LAST:event_btnHabitacionesActionPerformed

    private void btnCateogriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCateogriaActionPerformed
        try {
            jdiCategoria g = new jdiCategoria();
            
            g.toFront();
            
            g.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al acceder a la Aplicacion.", "Verifique el Error", 0);
        }

    }//GEN-LAST:event_btnCateogriaActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        
        try {
            jdiProducto pro = new jdiProducto();
            pro.toFront();
            pro.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al acceder a la Aplicacion.", "Verifique el Error", 0);
        }

    }//GEN-LAST:event_btnProductosActionPerformed

    private void descMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descMouseClicked
        if (JOptionPane.showConfirmDialog(this, "Esta a punto de\ncerrar la sesión\n¿Desea continuar?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION, 0,
                new ImageIcon(getClass().getResource("/Imagenes/principal/preg2.png"))) == JOptionPane.YES_OPTION) {
            this.dispose();
            new jdiLogin().setVisible(true);
        }
    }//GEN-LAST:event_descMouseClicked

    private void btnRservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRservaActionPerformed
        
        jdiaRegistrarReserva ca = new jdiaRegistrarReserva();
              ca.toFront();
       
        ca.setVisible(true);
           
        
         jdiaRegistrarReserva.txtidTrabajadorReserva.setText(LblIdPrincipal.getText());
        jdiaRegistrarReserva.txtNombreTRabajdorReserva.setText(lblNombreUPrincipal.getText() + " "+ lblPaternoUPrincipal.getText());
           jdiaRegistrarReserva.idusuarioReserva = Integer.parseInt(LblIdPrincipal.getText());

    }//GEN-LAST:event_btnRservaActionPerformed

    private void escritorioMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escritorioMenuMouseClicked
        cargarImagenesEnBotones();
    }//GEN-LAST:event_escritorioMenuMouseClicked
  FrmConcultas consulta;
    private void rSButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton11ActionPerformed
     consulta=new FrmConcultas();
     consulta.toFront();
     consulta.setVisible(true);
    }//GEN-LAST:event_rSButton11ActionPerformed

    private void btnCategoriaTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaTodoActionPerformed
  try {
            jdiCategoria g = new jdiCategoria();
            
            g.toFront();
            
            g.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al acceder a la Aplicacion.", "Verifique el Error", 0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCategoriaTodoActionPerformed

    private void btnHabitacionesTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionesTodoActionPerformed
  try {
            jdialogRegistroHabitaciones f = new jdialogRegistroHabitaciones();
            f.toFront();
            f.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al acceder a la Aplicacion.", "Verifique el Error", 0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnHabitacionesTodoActionPerformed

    private void btnClientesTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesTodoActionPerformed
     try {
            jDialogCliente g = new jDialogCliente();
            g.toFront();
            g.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al acceder a la Aplicacion.", "Verifique el Error", 0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesTodoActionPerformed

    private void btnProductosTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosTodoActionPerformed
   try {
            jdiProducto pro = new jdiProducto();
            pro.toFront();
            pro.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al acceder a la Aplicacion.", "Verifique el Error", 0);
        }        
    }//GEN-LAST:event_btnProductosTodoActionPerformed

    private void btnTrbajadoresTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrbajadoresTodoActionPerformed
  try {
            jdiTrabajador d = new jdiTrabajador();
            d.toFront();
            d.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al acceder a la Aplicacion.", "Verifique el Error", 0);
            
        }       
    }//GEN-LAST:event_btnTrbajadoresTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSPanelsSlider Escritorio;
    public static javax.swing.JLabel LblIdPrincipal;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private rojeru_san.RSButton btnCategoriaTodo;
    public static rojeru_san.RSButton btnCateogria;
    public static rojeru_san.RSButton btnClientes;
    private rojeru_san.RSButton btnClientesTodo;
    public static rojeru_san.RSButton btnHabitaciones;
    private rojeru_san.RSButton btnHabitacionesTodo;
    private rojeru_san.RSButton btnPrincipal;
    private rojeru_san.RSButton btnProductos;
    private rojeru_san.RSButton btnProductosTodo;
    public static rojeru_san.RSButton btnRserva;
    public static rojeru_san.RSButton btnTrabajadores;
    public static rojeru_san.RSButton btnTrbajadoresTodo;
    private principal.MaterialButton cerrar;
    private principal.MaterialButtomRectangle cerrarSesion;
    private javax.swing.JLabel desc;
    private rojeru_san.RSPanelShadow escritorioMenu;
    private javax.swing.JTabbedPane escritorioTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private com.icm.components.metro.LabelMetroICM labelMetroICM1;
    public static javax.swing.JLabel lblAccesoUPrincipal;
    public static javax.swing.JLabel lblMaternoUPrincipal;
    public static javax.swing.JLabel lblNombreUPrincipal;
    public static javax.swing.JLabel lblPaternoUPrincipal;
    private javax.swing.JLabel logoSexo;
    private principal.MaterialButton minimizar;
    private rojeru_san.RSButton rSButton11;
    public static javax.swing.JLabel userConect1;
    // End of variables declaration//GEN-END:variables
}
