/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaDominio.vHabitacion;
import CapaPersistencia.conexion;
import CapaPersistencia.fHabitacionesDAO;

import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Antonio AB
 */
public class jdialogRegistroHabitaciones extends javax.swing.JFrame {

    /**
     * Creates new form jdialogRegistroHabitaciones
     */
    public jdialogRegistroHabitaciones() {
        initComponents();
        mostrar("");
        inhabilitar();
        this.setLocationRelativeTo(null);
    }

    private String accion = "guardar";

    void inhabilitar() {
        txtIdHabitacion.setVisible(false);
        cboPiso.setEnabled(false);
        txtNhabitacion.setEnabled(false);
        txtDescripcion.setEnabled(false);
        txtPrecio.setEnabled(false);
        cboEstado.setEnabled(false);
        cbotipo_habitacion.setEnabled(false);

        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnEliminar.setEnabled(false);
        txtIdHabitacion.setText("");
        txtPrecio.setText("");
        txtDescripcion.setText("");
       
    }

    void habilitar() {
        txtIdHabitacion.setVisible(false);
        cboPiso.setEnabled(true);
        txtNhabitacion.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtPrecio.setEnabled(true);
        cboEstado.setEnabled(true);
        cbotipo_habitacion.setEnabled(true);

        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnEliminar.setEnabled(true);
        txtIdHabitacion.setText("");
        txtPrecio.setText("");
        txtDescripcion.setText("");

    }

    public void ocultarColumasProdcuto() {
        tablaRegistroHabitacion.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaRegistroHabitacion.getColumnModel().getColumn(0).setMinWidth(0);
        tablaRegistroHabitacion.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaRegistroHabitacion.getColumnModel().getColumn(3).setMaxWidth(0);
        tablaRegistroHabitacion.getColumnModel().getColumn(3).setMinWidth(0);
        tablaRegistroHabitacion.getColumnModel().getColumn(3).setPreferredWidth(0);
    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            fHabitacionesDAO func = new fHabitacionesDAO();
            modelo = func.mostrar(buscar);
            tablaRegistroHabitacion.setModel(modelo);
            lbltotalregistros.setText("Total Registros " + Integer.toString(func.totalRegistros));
            ocultarColumasProdcuto();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Error al mostrar " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel3 = new org.edisoncor.gui.panel.Panel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        txtIdTidpoHabitacion = new rojeru_san.RSMTextFull();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        txtPrecio = new rojeru_san.RSMTextFull();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        cboEstado = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        cbotipo_habitacion = new com.icm.components.metro.ComboboxMetroICM();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistroHabitacion = new com.icm.components.metro.TableMetroICM();
        btnBuscar = new rojeru_san.RSButton();
        txtBuscar = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        idDireciones = new com.icm.components.metro.LabelMetroICM();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        txtIdHabitacion = new rojeru_san.RSMTextFull();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        txtNhabitacion = new rojeru_san.RSMTextFull();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        cboPiso = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnNuevo = new rojeru_san.RSButton();
        btnGuardar = new rojeru_san.RSButton();
        btnEliminar = new rojeru_san.RSButton();
        btnCancelar = new rojeru_san.RSButton();
        btnSalir = new rojeru_san.RSButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        lbltotalregistros = new javax.swing.JLabel();
        btnRegistroTipoHabitacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        panel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel3.setForeground(new java.awt.Color(255, 255, 255));
        panel3.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel3.setColorSecundario(new java.awt.Color(204, 204, 204));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Corridor_18px.png"))); // NOI18N
        jXLabel5.setText("IDTipo Habitacion:");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel3.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, -1, -1));

        txtIdTidpoHabitacion.setBackground(new java.awt.Color(153, 153, 153));
        txtIdTidpoHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        txtIdTidpoHabitacion.setPlaceholder("");
        panel3.add(txtIdTidpoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 13, 200, -1));

        jXLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Money_Bag_18px.png"))); // NOI18N
        jXLabel6.setText("Precio:");
        jXLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel3.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        txtPrecio.setBackground(new java.awt.Color(153, 153, 153));
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setPlaceholder("");
        txtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioFocusLost(evt);
            }
        });
        panel3.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 110, -1));

        jXLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Resume_18px.png"))); // NOI18N
        jXLabel7.setText("Descripcion:");
        jXLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel3.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jXLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Transaction_List_18px.png"))); // NOI18N
        jXLabel4.setText("Estado");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel3.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        cboEstado.setBackground(new java.awt.Color(102, 102, 102));
        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "Mantenimiento", "Ocupada", "Disponible", " " }));
        panel3.add(cboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 174, -1));

        txtDescripcion.setBackground(new java.awt.Color(102, 102, 102));
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescripcionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescripcionFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(txtDescripcion);

        panel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 202, 69));

        jXLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Hotel_18px.png"))); // NOI18N
        jXLabel8.setText("Tipo Habitacion:");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panel3.add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 66, -1, -1));

        cbotipo_habitacion.setBackground(new java.awt.Color(204, 204, 204));
        cbotipo_habitacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, null, java.awt.Color.gray, java.awt.Color.gray));
        cbotipo_habitacion.setEditable(true);
        cbotipo_habitacion.setForeground(new java.awt.Color(153, 153, 153));
        panel3.add(cbotipo_habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 200, -1));

        tablaRegistroHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaRegistroHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRegistroHabitacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaRegistroHabitacion);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Categoria/icons8_Search_32px_1.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        idDireciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Google_Web_Search_18px.png"))); // NOI18N
        idDireciones.setText("Buscar:");

        rSPanelShadow1.setBackground(new java.awt.Color(102, 102, 102));

        txtIdHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtIdHabitacion.setBordeColorNoFocus(new java.awt.Color(0, 0, 0));
        txtIdHabitacion.setPlaceholder("Escribe el ID habitacion...");

        jXLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Room_18px.png"))); // NOI18N
        jXLabel2.setText("N° Habitacion:");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtNhabitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtNhabitacion.setBordeColorNoFocus(new java.awt.Color(0, 0, 0));
        txtNhabitacion.setPlaceholder("Escribe N° de Habitacion");
        txtNhabitacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNhabitacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNhabitacionFocusLost(evt);
            }
        });

        jXLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Stairs_Up_18px.png"))); // NOI18N
        jXLabel3.setText("Piso:");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        cboPiso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "N° 1", "N° 2", "N° 3", "N° 4", "N° 5", "N° 6", "N° 7", "N° 8", " ", " " }));

        javax.swing.GroupLayout rSPanelShadow1Layout = new javax.swing.GroupLayout(rSPanelShadow1);
        rSPanelShadow1.setLayout(rSPanelShadow1Layout);
        rSPanelShadow1Layout.setHorizontalGroup(
            rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(rSPanelShadow1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(txtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelShadow1Layout.createSequentialGroup()
                        .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rSPanelShadow1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNhabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rSPanelShadow1Layout.setVerticalGroup(
            rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNhabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 204, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GESTION DE REGISTRO DE HABITACIONES ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel6)
                .addContainerGap(573, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newPago.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar habitacion.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/deleteHabitacion.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelRoom.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirConsumo.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jInternalFrame1.setMinimumSize(new java.awt.Dimension(40, 40));
        jInternalFrame1.setName(""); // NOI18N
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Report_Card_32px.png"))); // NOI18N
        jMenu3.setText("Reportes");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Bed_20px.png"))); // NOI18N
        jMenuItem2.setText("Reporte Habitaciones");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jInternalFrame1.setJMenuBar(jMenuBar2);

        jTabbedPane1.addTab("Reportes Habitaciones", jInternalFrame1);

        lbltotalregistros.setText("Registros");

        btnRegistroTipoHabitacion.setText("....");
        btnRegistroTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroTipoHabitacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(idDireciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(90, 90, 90)
                                    .addComponent(btnRegistroTipoHabitacion))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rSPanelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(10, 10, 10)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnRegistroTipoHabitacion)))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(rSPanelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(idDireciones, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbltotalregistros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusGained
        txtPrecio.setForeground(Color.red);
        txtPrecio.setBackground(Color.yellow);
    }//GEN-LAST:event_txtPrecioFocusGained

    private void txtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusLost
        txtPrecio.setBackground(Color.GREEN);
    }//GEN-LAST:event_txtPrecioFocusLost

    private void txtDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescripcionFocusGained
        txtDescripcion.setForeground(Color.red);
        txtDescripcion.setBackground(Color.yellow);
    }//GEN-LAST:event_txtDescripcionFocusGained

    private void txtDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescripcionFocusLost
        txtDescripcion.setBackground(Color.GREEN);
    }//GEN-LAST:event_txtDescripcionFocusLost

    private void tablaRegistroHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRegistroHabitacionMouseClicked
        try {
            btnGuardar.setText("Editar");
            habilitar();
            btnEliminar.setEnabled(true);
            accion = "editar";
            int fila = tablaRegistroHabitacion.rowAtPoint(evt.getPoint());
            txtIdHabitacion.setText(tablaRegistroHabitacion.getValueAt(fila, 0).toString());
            txtNhabitacion.setText(tablaRegistroHabitacion.getValueAt(fila, 1).toString());
            cboPiso.setSelectedItem(tablaRegistroHabitacion.getValueAt(fila, 2).toString());
            txtIdTidpoHabitacion.setText(tablaRegistroHabitacion.getValueAt(fila, 3).toString());
            cbotipo_habitacion.setSelectedItem(tablaRegistroHabitacion.getValueAt(fila, 4).toString());
           JOptionPane.showMessageDialog(null, tablaRegistroHabitacion.getValueAt(fila, 4).toString());
            txtPrecio.setText(tablaRegistroHabitacion.getValueAt(fila, 5).toString());
            txtDescripcion.setText(tablaRegistroHabitacion.getValueAt(fila, 6).toString());
            cboEstado.setSelectedItem(tablaRegistroHabitacion.getValueAt(fila, 7).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error no se ha podido hacer el cambio: " + e);
        }

    }//GEN-LAST:event_tablaRegistroHabitacionMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        mostrar(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNhabitacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNhabitacionFocusGained
        // TODO add your handling code here:
        txtNhabitacion.setForeground(Color.red);
        txtNhabitacion.setBackground(Color.yellow);
    }//GEN-LAST:event_txtNhabitacionFocusGained

    private void txtNhabitacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNhabitacionFocusLost
        txtNhabitacion.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtNhabitacionFocusLost

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        try {
            habilitar();
            btnGuardar.setText("Guardar");
            accion = "guardar";
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error En la Aplicacion", "Error en Boton Nuevo:" + e, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {

            vHabitacion dts = new vHabitacion();
            fHabitacionesDAO func = new fHabitacionesDAO();

            int verificarNumeroHabitacion = Integer.parseInt(txtNhabitacion.getText());
            int num_Habitacion = func.numerohabitacionIgual(verificarNumeroHabitacion);

            int seleccionado = cboPiso.getSelectedIndex();
            if (num_Habitacion == verificarNumeroHabitacion) {
                JOptionPane.showMessageDialog(null, "YA EXISTE UNA HABITACION CON EL MISMO CODIGO");
                txtNhabitacion.requestFocus();
                return;
            }
            dts.setHabitacionNumero(Integer.parseInt(txtNhabitacion.getText()));

            dts.setHabitacionPiso((String) cboPiso.getItemAt(seleccionado));
            dts.setIdTipoHabitacion(Integer.parseInt(txtIdTidpoHabitacion.getText()));
            seleccionado = cboEstado.getSelectedIndex();
            dts.setHabitacionEsatdo((String) cboEstado.getItemAt(seleccionado));
            if (accion.equals("guardar")) {
                if (func.insertar(dts)) {
                    JOptionPane.showMessageDialog(rootPane, "La habitación fue registrada satisfactoriamente");
                    mostrar("");
                    inhabilitar();
                }
            } else if (accion.equals("editar")) {
                dts.setIdHabitacion(Integer.parseInt(txtIdHabitacion.getText()));
                if (func.editar(dts)) {
                    JOptionPane.showMessageDialog(rootPane, "La habitación fue Editada satisfactoriamente");
                    mostrar("");
                    inhabilitar();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error Al Gurdar", "Boton Guardar:" + e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        try {
            if (!txtIdHabitacion.getText().equals("")) {
                int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estás seguro de Eliminar la Habitación?", "Confirmar", 2);

                if (confirmacion == 0) {
                    fHabitacionesDAO func = new fHabitacionesDAO();
                    vHabitacion dts = new vHabitacion();

                    dts.setIdHabitacion(Integer.parseInt(txtIdHabitacion.getText()));
                    func.eliminar(dts);
                    mostrar("");
                    inhabilitar();

                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Eliminar :" + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        inhabilitar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        if (JOptionPane.showConfirmDialog(this, "Esta a punto de\ncerrar la Ventana\n¿Desea continuar?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION, 0,
                new ImageIcon(getClass().getResource("/Imagenes/principal/preg2.png"))) == JOptionPane.YES_OPTION) {
            this.dispose();

        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Map p = new HashMap();
        JasperReport report;
        JasperPrint print;
        try {
            report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
                    + "/src/ReporteHotel/ReporteHotel.jrxml");
            print = JasperFillManager.fillReport(report, p, connection);
            JasperViewer view = new JasperViewer(print, false);
            view.setTitle("Reporte de Habitaciones");

            view.toFront();
            view.show();
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnRegistroTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroTipoHabitacionActionPerformed
        jdiTipoHabitacion tph = new jdiTipoHabitacion();
        tph.setVisible(true);
    }//GEN-LAST:event_btnRegistroTipoHabitacionActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
   x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
               this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);

    }//GEN-LAST:event_formMouseDragged
    private Connection connection = new conexion().conectar();
    int x, y;
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(jdialogRegistroHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(jdialogRegistroHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(jdialogRegistroHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(jdialogRegistroHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new jdialogRegistroHabitaciones().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnBuscar;
    private rojeru_san.RSButton btnCancelar;
    private rojeru_san.RSButton btnEliminar;
    private rojeru_san.RSButton btnGuardar;
    private rojeru_san.RSButton btnNuevo;
    private javax.swing.JButton btnRegistroTipoHabitacion;
    private rojeru_san.RSButton btnSalir;
    public static javax.swing.JComboBox cboEstado;
    private javax.swing.JComboBox cboPiso;
    public static com.icm.components.metro.ComboboxMetroICM cbotipo_habitacion;
    private com.icm.components.metro.LabelMetroICM idDireciones;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private javax.swing.JLabel lbltotalregistros;
    private org.edisoncor.gui.panel.Panel panel3;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private com.icm.components.metro.TableMetroICM tablaRegistroHabitacion;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtBuscar;
    public static javax.swing.JTextArea txtDescripcion;
    private rojeru_san.RSMTextFull txtIdHabitacion;
    public static rojeru_san.RSMTextFull txtIdTidpoHabitacion;
    private rojeru_san.RSMTextFull txtNhabitacion;
    public static rojeru_san.RSMTextFull txtPrecio;
    // End of variables declaration//GEN-END:variables
}
