/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaDominio.vCategoria;
import CapaDominio.vPersonaDirecciones;
import CapaPersistencia.fCategoriaDAO;
import CapaPersistencia.fDireccionesDAO;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import principal.PrincipalHotel;

/**
 *
 * @author Antonio AB
 */
public class JdalogPersonasDirecciones extends javax.swing.JDialog {

    public JdalogPersonasDirecciones() {
        super(PrincipalHotel.getInstancia(), true);
        initComponents();
        mostrar("");
        inhabilitarTextos();
        controles(true);

    }
    private String accion = "guardar";

    public void habilitarTextos() {
        txtIdDireciones.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtNumero.setEnabled(true);
        txtCorreo.setEnabled(true);
    }

    public void inhabilitarTextos() {
        txtIdDireciones.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtNumero.setEnabled(false);
        txtCorreo.setEnabled(false);
    }

    public void limpiarTextos() {
        txtIdDireciones.setText("");
        txtDireccion.setText("");
        txtNumero.setText("");
        txtCorreo.setText("");
    }

    void controles(boolean sw) {
        btnNuevo.setEnabled(sw);
        btnGuardar.setEnabled(sw);
        btnCancelar.setEnabled(!sw);
        btnBuscar.setEnabled(sw);
        btnEliminar.setEnabled(sw);

    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            fDireccionesDAO func = new fDireccionesDAO();
            modelo = func.mostrar(buscar);
            tablaDirecciones.setModel(modelo);
            lbltotal_RegistrosCategoria.setText("Total Registros  " + Integer.toString(func.totalRegistros));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Error al mostrar" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        panel2 = new org.edisoncor.gui.panel.Panel();
        btnSalir = new rojeru_san.RSButton();
        btnNuevo = new rojeru_san.RSButton();
        btnGuardar = new rojeru_san.RSButton();
        btnEliminar = new rojeru_san.RSButton();
        btnCancelar = new rojeru_san.RSButton();
        idDireciones = new com.icm.components.metro.LabelMetroICM();
        idDireciones1 = new com.icm.components.metro.LabelMetroICM();
        idDireciones2 = new com.icm.components.metro.LabelMetroICM();
        idDireciones3 = new com.icm.components.metro.LabelMetroICM();
        txtNumero = new org.edisoncor.gui.textField.TextFieldRectBackground();
        txtIdDireciones = new org.edisoncor.gui.textField.TextFieldRectBackground();
        txtDireccion = new org.edisoncor.gui.textField.TextFieldRectBackground();
        txtCorreo = new org.edisoncor.gui.textField.TextFieldRectBackground();
        textFieldRectBackground4 = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDirecciones = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        idDireciones4 = new com.icm.components.metro.LabelMetroICM();
        txtBuscar = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        lbltotal_RegistrosCategoria = new javax.swing.JLabel();
        idDireciones5 = new com.icm.components.metro.LabelMetroICM();
        txtidPersona = new org.edisoncor.gui.textField.TextFieldRectBackground();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setColorPrimario(new java.awt.Color(51, 153, 255));
        panel1.setColorSecundario(new java.awt.Color(0, 102, 102));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 110, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 110, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 110, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 110, -1));

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        idDireciones.setText("Buscar:");
        panel1.add(idDireciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, 20));

        idDireciones1.setText("idDireciones:");
        panel1.add(idDireciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        idDireciones2.setText("Telefono:");
        panel1.add(idDireciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        idDireciones3.setText("Direccion:");
        panel1.add(idDireciones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtNumero.setDescripcion("Ingrese numero Telefonico");
        panel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 210, -1));

        txtIdDireciones.setDescripcion("ID");
        panel1.add(txtIdDireciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 210, -1));

        txtDireccion.setDescripcion("");
        panel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 210, -1));

        txtCorreo.setDescripcion("ejemplo@gmail.com");
        panel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 210, 20));
        panel1.add(textFieldRectBackground4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 210, -1));

        tablaDirecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDirecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDireccionesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaDireccionesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDirecciones);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 800, 250));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, -1, -1));

        idDireciones4.setText("Email:");
        panel1.add(idDireciones4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));
        panel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 220, -1));

        lbltotal_RegistrosCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltotal_RegistrosCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lbltotal_RegistrosCategoria.setText("Registros:");
        panel1.add(lbltotal_RegistrosCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 180, 20));

        idDireciones5.setText("IdPersona:");
        panel1.add(idDireciones5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));

        txtidPersona.setDescripcion("ejemplo@gmail.com");
        panel1.add(txtidPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 210, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        habilitarTextos();
        controles(true);
        btnGuardar.setText("Guardar");
        accion = "guardar";

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (txtDireccion.getText().compareTo("") != 0 && txtNumero.getText().compareTo("") != 0 && txtCorreo.getText().compareTo(" ") != 0) {
            vPersonaDirecciones dts = new vPersonaDirecciones();
            fDireccionesDAO func = new fDireccionesDAO();
            dts.setPersonaDireccionDireccion(txtDireccion.getText());
            dts.setPersonaDireccionTelefono(Integer.parseInt(txtNumero.getText()));
            dts.setPersonaDireccionCorreo(txtCorreo.getText());
            dts.setIdPersona(Integer.parseInt(txtidPersona.getText()));

            if (accion.equals("guardar")) {
                if (func.insertar(dts)) {
                    JOptionPane.showMessageDialog(rootPane, "Las Direciones fueron agregadas correctamente");
                    mostrar("");
                    limpiarTextos();
                    inhabilitarTextos();
                    controles(true);
                }

            } else if (accion.equals("editar")) {
                                    dts.setIdPersonaDireccion(Integer.parseInt(txtIdDireciones.getText()));

                if (func.editar(dts)) {
                    JOptionPane.showMessageDialog(rootPane, "Las Direciones fueron editas correctamente");
                    mostrar("");
                    limpiarTextos();
                    inhabilitarTextos();
                    controles(true);
                }
            }

        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarTextos();
        inhabilitarTextos();
        controles(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!txtIdDireciones.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Deseas Eliminar la Direcion?", "Confirmar", 2);
            if (confirmacion == 0) {
                fDireccionesDAO func = new fDireccionesDAO();
                vPersonaDirecciones dts = new vPersonaDirecciones();
                dts.setIdPersonaDireccion(Integer.parseInt(txtIdDireciones.getText()));
                func.eliminar(dts);
                mostrar("");
                inhabilitarTextos();
                controles(false);
                limpiarTextos();
            }

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        mostrar(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaDireccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDireccionesMouseClicked
        btnGuardar.setText("Editar");
        habilitarTextos();
        controles(true);
        btnEliminar.setEnabled(true);
        accion = "editar";
        int fila = tablaDirecciones.rowAtPoint(evt.getPoint());
        txtIdDireciones.setText(tablaDirecciones.getValueAt(fila, 0).toString());
        txtDireccion.setText(tablaDirecciones.getValueAt(fila, 1).toString());
        txtNumero.setText(tablaDirecciones.getValueAt(fila, 2).toString());
        txtCorreo.setText(tablaDirecciones.getValueAt(fila, 3).toString());

    }//GEN-LAST:event_tablaDireccionesMouseClicked

    private void tablaDireccionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDireccionesMousePressed
        if (evt.getClickCount() == 2) {
            int fila = tablaDirecciones.getSelectedRow();
            String id,telefono;
            String direccion,email;
            
            id=tablaDirecciones.getValueAt(fila, 0).toString();
            direccion=tablaDirecciones.getValueAt(fila, 1).toString();
            telefono=tablaDirecciones.getValueAt(fila, 2).toString();
            email=tablaDirecciones.getValueAt(fila, 3).toString();
            
//            jdiPersona.txtIdDirecciones.setText(id);
//            jdiPersona.txtDirecion.setText(direccion);
//            jdiPersona.txtTelefono.setText(telefono);
//            jdiPersona.txtEmail.setText(email);
//            this.setVisible(false);
            
           // jDialogCliente.txtIdDirecciones.setText(id);
            jDialogCliente.txtDireccion.setText(direccion);
             jDialogCliente.txtTelefono.setText(telefono);
            jDialogCliente.txtCorreo.setText(email);
            
//            jdiTrabajador.txtIddirecciones.setText(id);
//            jdiTrabajador.txtdireccion.setText(direccion);
//            jdiTrabajador.txttelefono.setText(telefono);
//            jdiTrabajador.txtemail.setText(email);
           this.setVisible(false);
        }
    }//GEN-LAST:event_tablaDireccionesMousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JdalogPersonasDirecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JdalogPersonasDirecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JdalogPersonasDirecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JdalogPersonasDirecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        </editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JdalogPersonasDirecciones dialog = new JdalogPersonasDirecciones(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private rojeru_san.RSButton btnCancelar;
    private rojeru_san.RSButton btnEliminar;
    private rojeru_san.RSButton btnGuardar;
    private rojeru_san.RSButton btnNuevo;
    private rojeru_san.RSButton btnSalir;
    private com.icm.components.metro.LabelMetroICM idDireciones;
    private com.icm.components.metro.LabelMetroICM idDireciones1;
    private com.icm.components.metro.LabelMetroICM idDireciones2;
    private com.icm.components.metro.LabelMetroICM idDireciones3;
    private com.icm.components.metro.LabelMetroICM idDireciones4;
    private com.icm.components.metro.LabelMetroICM idDireciones5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltotal_RegistrosCategoria;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private javax.swing.JTable tablaDirecciones;
    private org.edisoncor.gui.textField.TextFieldRectBackground textFieldRectBackground4;
    private org.edisoncor.gui.textField.TextFieldRoundBackground txtBuscar;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtCorreo;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtDireccion;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtIdDireciones;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtNumero;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtidPersona;
    // End of variables declaration//GEN-END:variables
}
